[default]
locale = 'en-gb'
extend-ignore-re = [
  "(?Rm)^.*(<!--|#|//)\\s*spellchecker:disable-line(-->|\n)?$",
  "(?s)(<!--|#|//)\\s*spellchecker:off\\s*(-->|\n).*?(<!--|#|//)\\s*spellchecker:on",
]

[files]
extend-exclude = [ "node_modules/**", ]
